create table if not exists public.todo_items (
  id bigint generated by default as identity primary key,
  task text not null,
  status text not null check (status in ('yapıldı','yapılmadı')),
  owner text not null default 'UBT',
  note text,
  sort_order int not null default 0,
  inserted_at timestamptz not null default now()
);

alter table public.todo_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'todo_items'
      and policyname = 'Allow anon select todo_items'
  ) then
    create policy "Allow anon select todo_items"
      on public.todo_items
      for select
      to anon
      using (true);
  end if;
end $$;

insert into public.todo_items (task, status, owner, note, sort_order)
select *
from (
  values
  ('Next.js App Router + TS + Tailwind kurulum', 'yapıldı', 'UBT', 'Production build başarılı.', 1),
  ('Ana sayfa, Hakkımda, İletişim, Yasal Uyarı, Eğitimler', 'yapıldı', 'UBT', 'Tüm temel sayfalar eklendi.', 2),
  ('Blog liste + yazı detay sayfaları', 'yapıldı', 'UBT', 'Mock data ile bağlı.', 3),
  ('SEO metadata, sitemap, robots', 'yapıldı', 'UBT', 'Canonical ve OG/Twitter dahil.', 4),
  ('Header’da çalışma masası temalı görsel', 'yapıldı', 'UBT', 'Hero için optimize SVG eklendi.', 5),
  ('Yazı kartları tasarımı', 'yapıldı', 'UBT', 'Sade ve okunaklı kart yapısı eklendi.', 6),
  ('Hero alanının nihai düzeni', 'yapıldı', 'UBT', 'Başlık, açıklama ve CTA ile tamamlandı.', 7),
  ('Instagram linki netleştirme', 'yapılmadı', 'UBT', 'Şimdilik placeholder alanı var.', 8)
) as seed(task, status, owner, note, sort_order)
where not exists (select 1 from public.todo_items);