create table if not exists public.content_todos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  status text not null default 'pending' check (status in ('pending', 'in_progress', 'completed', 'cancelled')),
  related_post_id bigint references public.posts(id) on delete set null,
  due_date timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_content_todos_status on public.content_todos(status);
create index if not exists idx_content_todos_related_post on public.content_todos(related_post_id);

alter table public.content_todos enable row level security;

create policy "Allow anon all on content_todos"
  on public.content_todos for all
  to anon using (true) with check (true);

create trigger set_content_todos_updated_at
  before update on public.content_todos
  for each row execute function public.handle_updated_at();

insert into public.content_todos (title, description, priority, status) values
  ('Haftalik bulten formatini belirle', 'Cuma gunleri yayinlanacak bulten sablonu hazirlanacak', 'high', 'pending'),
  ('Portfoy yonetimi baslangic yazisi SEO optimizasyonu', 'title ve description eksik', 'medium', 'in_progress'),
  ('Yazarlar icin markdown editor alternatiflerini arastir', null, 'low', 'pending');
