create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  featured_image_url text,
  status text not null default 'draft' check (status in ('draft', 'review', 'scheduled', 'published', 'archived')),
  featured boolean not null default false,
  category_id bigint references public.categories(id) on delete set null,
  author_id text,
  author_name text not null default 'Ali Fuat Aslan',
  published_at timestamptz,
  scheduled_at timestamptz,
  reading_time text,
  seo_title text,
  seo_description text,
  canonical_url text,
  og_image_url text,
  disclaimer_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_tags (
  post_id bigint not null references public.posts(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (post_id, tag_id)
);

create index if not exists idx_posts_slug on public.posts(slug);
create index if not exists idx_posts_status on public.posts(status);
create index if not exists idx_posts_published_at on public.posts(published_at desc);
create index if not exists idx_posts_category_id on public.posts(category_id);
create index if not exists idx_posts_featured on public.posts(featured) where featured = true;
create index if not exists idx_categories_slug on public.categories(slug);
create index if not exists idx_tags_slug on public.tags(slug);

alter table public.categories enable row level security;
alter table public.tags enable row level security;
alter table public.posts enable row level security;
alter table public.post_tags enable row level security;

create policy "Allow anon read categories"
  on public.categories for select
  to anon using (true);

create policy "Allow anon read tags"
  on public.tags for select
  to anon using (true);

create policy "Allow anon read published posts"
  on public.posts for select
  to anon using (status = 'published');

create policy "Allow anon read post_tags"
  on public.post_tags for select
  to anon using (true);

create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_categories_updated_at
  before update on public.categories
  for each row execute function public.handle_updated_at();

create trigger set_posts_updated_at
  before update on public.posts
  for each row execute function public.handle_updated_at();

insert into public.categories (name, slug, description) values
  ('Piyasa Yorumlari', 'piyasa-yorumlari', 'Borsa ve guncel makro bakis'),
  ('Analiz Okulu', 'analiz-okulu', 'Teknik ve temel analiz egitim yazilari'),
  ('Finans Tarihi', 'finans-tarihi', 'Gecmis krizler ve piyasa olaylarinin analizi'),
  ('Yatirim Araclari', 'yatirim-araclari', 'Borsa, Fon, Bono, Eurobond ve BES uzerine rehber icerikler'),
  ('Bilanco Analizi', 'bilanco-analizi', 'Sirket finansallarinin yorumlanmasi'),
  ('Strateji & Psikoloji', 'strateji-psikoloji', 'Yatirimci disiplini ve portfoy yonetimi')
on conflict (slug) do nothing;

insert into public.tags (name, slug) values
  ('psikoloji', 'psikoloji'),
  ('risk yonetimi', 'risk-yonetimi'),
  ('davranissal finans', 'davranissal-finans'),
  ('teknik analiz', 'teknik-analiz'),
  ('trend', 'trend'),
  ('egitim', 'egitim'),
  ('kriz', 'kriz'),
  ('tarih', 'tarih'),
  ('risk', 'risk'),
  ('eurobond', 'eurobond'),
  ('sabit getirili', 'sabit-getirili'),
  ('finans okuryazarligi', 'finans-okuryazarligi'),
  ('bilanco', 'bilanco'),
  ('finansal tablolar', 'finansal-tablolar'),
  ('temel analiz', 'temel-analiz'),
  ('makro', 'makro'),
  ('enflasyon', 'enflasyon'),
  ('faiz', 'faiz')
on conflict (slug) do nothing;

insert into public.posts (title, slug, excerpt, content, featured_image_url, status, featured, category_id, author_name, published_at, reading_time, seo_title, seo_description, disclaimer_enabled)
select
  p.title, p.slug, p.excerpt, p.content, p.featured_image_url, p.status, p.featured, c.id, p.author_name, p.published_at::timestamptz, p.reading_time, p.seo_title, p.seo_description, p.disclaimer_enabled
from (
  values
    ('Piyasalarda Belirsizlik Donemlerinde Yatirimci Psikolojisi', 'belirsizlik-donemlerinde-yatirimci-psikolojisi',
     'Volatil donemlerde duygusal kararlarin onune gecmek icin uygulanabilir bir dusunce cercevesi.',
     'Belirsizlik donemleri, yatirimcilarin hem risk algisini hem de karar alma hizini etkiler. Bu yazida, davranissal finans literaturundeki temel kavramlar isigi altinda panik ve asiri ozguven tuzaklarini ele aliyoruz. Icerik egitsel amaclidir ve herhangi bir yatirim tavsiyesi icermez.',
     '/images/hero-desk.svg', 'published', true, 'Strateji & Psikoloji', 'Ali Fuat Aslan', '2026-03-20', '7 dk', null, null, true),
    ('Teknik Analizde Trend Okuma Disiplini', 'teknik-analizde-trend-okuma-disiplini',
     'Trend kavramini sade bir sistematikle yorumlamak ve gereksiz islem yogunlugunu azaltmak.',
     'Trend analizi, fiyat hareketlerini baglam icinde okumayi gerektirir. Bu yazida trendin gucu, zaman dilimi secimi ve teyit mekanizmalari gibi temel basliklari egitsel bir perspektifle ozetliyoruz.',
     '/images/hero-desk.svg', 'published', true, 'Analiz Okulu', 'Ali Fuat Aslan', '2026-03-14', '6 dk', null, null, true),
    ('Finans Tarihinden Ogrenilecek 5 Buyuk Kriz Dersi', 'finans-tarihinden-5-buyuk-kriz-dersi',
     'Gecmis krizlerden bugune tasinabilecek risk, likidite ve psikoloji dersleri.',
     'Finansal krizler tekrar eden davranis kaliplari ve yapisal kirilganliklar uzerinden okunabilir. Bu icerikte, tarihsel ornekler uzerinden uzun vadeli dusunce disiplinine odaklaniyoruz.',
     '/images/hero-desk.svg', 'published', true, 'Finans Tarihi', 'Ali Fuat Aslan', '2026-03-09', '8 dk', null, null, true),
    ('Eurobond Nedir ve Nasil Degerlendirilir?', 'eurobond-nedir-ve-nasil-degerlendirilir',
     'Eurobond enstrumanlarinin temel yapisi, getiri dinamikleri ve risk boyutlari.',
     'Eurobondlar, doviz bazli borclanma araclari olarak farkli risk-getiri profilleri sunar. Bu yazida vade, kupon, ihracci riski ve faiz iliskisi gibi ana basliklara odaklaniyoruz.',
     '/images/hero-desk.svg', 'published', false, 'Yatirim Araclari', 'Ali Fuat Aslan', '2026-03-03', '5 dk', null, null, true),
    ('Bilanco Okurken Ilk Bakilmasi Gereken Kalemler', 'bilanco-okurken-ilk-bakilmasi-gereken-kalemler',
     'Gelir tablosu, nakit akisi ve bilanco iliskisini sade bir okuma sirasiyla ele aliyoruz.',
     'Bilanco analizi yalnizca oran hesaplamak degildir; is modelini anlamayi gerektirir. Bu yazida likidite, borcluluk ve karlilik ekseninde pratik bir okuma cercevesi sunuyoruz.',
     '/images/hero-desk.svg', 'published', false, 'Bilanco Analizi', 'Ali Fuat Aslan', '2026-02-26', '9 dk', null, null, true),
    ('Piyasa Notlari: Makro Gosterge Okumasi Neden Onemli?', 'piyasa-notlari-makro-gosterge-okumasi',
     'Faiz, enflasyon ve buyume verilerinin piyasa beklentilerini nasil sekillendirdigine dair bir cerceve.',
     'Makro veriler, sirket performansini dolayli olarak etkileyen temel sinyalleri barindirir. Bu icerikte veri takvimi disiplinini ve yorumlama tuzaklarini degerlendiriyoruz.',
     '/images/hero-desk.svg', 'published', false, 'Piyasa Yorumlari', 'Ali Fuat Aslan', '2026-02-19', '6 dk', null, null, true)
) as p(title, slug, excerpt, content, featured_image_url, status, featured, cat_name, author_name, published_at, reading_time, seo_title, seo_description, disclaimer_enabled)
join public.categories c on c.name = p.cat_name
where not exists (select 1 from public.posts where slug = p.slug);

insert into public.post_tags (post_id, tag_id)
select po.id, t.id
from public.posts po
cross join public.tags t
where po.slug = 'belirsizlik-donemlerinde-yatirimci-psikolojisi' and t.slug in ('psikoloji', 'risk-yonetimi', 'davranissal-finans')
   or po.slug = 'teknik-analizde-trend-okuma-disiplini' and t.slug in ('teknik-analiz', 'trend', 'egitim')
   or po.slug = 'finans-tarihinden-5-buyuk-kriz-dersi' and t.slug in ('kriz', 'tarih', 'risk')
   or po.slug = 'eurobond-nedir-ve-nasil-degerlendirilir' and t.slug in ('eurobond', 'sabit-getirili', 'finans-okuryazarligi')
   or po.slug = 'bilanco-okurken-ilk-bakilmasi-gereken-kalemler' and t.slug in ('bilanco', 'finansal-tablolar', 'temel-analiz')
   or po.slug = 'piyasa-notlari-makro-gosterge-okumasi' and t.slug in ('makro', 'enflasyon', 'faiz')
on conflict do nothing;
